.PHONY: deploy

deploy:
    GOOS=linux GOARCH=amd64 go build -o ./auth-service/build/main ./auth-service/cmd/main.go   
    GOOS=linux GOARCH=amd64 go build -o ./email-service/build/main ./email-service/main.go
    zip -r ./deploy-scripts/auth-service.zip ./auth-service
    zip -r ./deploy-scripts/email-service.zip ./email-service
    cd deploy-scripts && cdk deploy 