basePath: /api/v1
definitions:
  doc_model.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  doc_model.Login:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  doc_model.OTP:
    properties:
      email:
        type: string
      otp:
        type: string
    type: object
  doc_model.Register:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      middle_name:
        type: string
      password:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  doc_model.SuccessResponse:
    properties:
      token:
        type: string
    type: object
  domain.User:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      middlename:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: This is a registration api for an application.
  title: Registration API
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: Allows users to login into their account.
      parameters:
      - description: User's email and password
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/doc_model.Login'
      produces:
      - application/json
      responses:
        "201":
          description: 'Successful response : Bearer \<token\>'
          schema:
            $ref: '#/definitions/doc_model.SuccessResponse'
        "400":
          description: Invalid JSON data, Invalid Email
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "401":
          description: Please Verify Your Account, Invalid Credentials
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "404":
          description: User is not registered
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "422":
          description: Please Verify Your Account
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
      summary: Login route
      tags:
      - user
  /user/otp:
    post:
      consumes:
      - application/json
      description: Allows users to validate OTP and complete the registration process.
      parameters:
      - description: User's email address and otp
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/doc_model.OTP'
      produces:
      - application/json
      responses:
        "200":
          description: 'Successful response : Bearer \<token\>'
          schema:
            $ref: '#/definitions/doc_model.SuccessResponse'
        "400":
          description: Invalid JSON data, Invalid Email
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "401":
          description: Invalid OTP, User Already Verified
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "404":
          description: User Not Found
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
      summary: Validation route
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: Allows users to create a new account.
      parameters:
      - description: User's firstname, lastname, middlename, email, password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/doc_model.Register'
      produces:
      - application/json
      responses:
        "201":
          description: 'Successful response : User Model'
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Invalid JSON data, Invalid Email
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "422":
          description: Please provide with sufficient credentials
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
        "500":
          description: Internal Server Error, Error in inserting the document, Error
            in hashing password, Error While generating OTP
          schema:
            $ref: '#/definitions/doc_model.ErrorResponse'
      summary: Register route
      tags:
      - user
swagger: "2.0"
