# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: BlckPr-auth pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean
        run: make clean

  build:
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - name: Build
        run: make build
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      SQLURI: ${{ secrets.SQLURI }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_LIFETIME: ${{ secrets.JWT_LIFETIME }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ADMIN: ${{ secrets.ADMIN }}
      SEND_TO_EMAIL_ARN: ${{ secrets.SEND_TO_EMAIL_ARN }}
      CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install AWS CDK
      run: |
        npm install -g aws-cdk
        
    # - name: CDK Synth
    #   run: cdk synth
        
    # - name: CDK Bootstrap
    #   run: cdk bootstrap
        
    - name: CDK Deploy
      run: make deploy

